package com.jonathanpli.exceptionnull.controller.helpers;

import java.util.Map;
import java.util.HashMap;

import com.mitchellbosecke.pebble.extension.AbstractExtension;
import com.google.common.collect.ImmutableMap;

/**
 * Provides Exception Null-specific contexts for all templates
 * generated by Pebble
 */
public class PebbleExtension extends AbstractExtension {
    private Map<String, Object> globals;

    public PebbleExtension() {
        Map<String, Object> values = new HashMap<>();
        values.put("paths", getPaths());

        globals = ImmutableMap.copyOf(values);
    }

    @Override
    public Map<String, Object> getGlobalVariables() {
        return globals;
    }

    // TODO:(jonathan) Fix for clarity while mainintaing compatibility with Pebble templating
    private String[][] getPaths() {
        String[][] paths = {
            { "/", "Home" },
            { "/arena", "Arena" }
        };
        return paths;
    }
}
